name: j1_router
description: A router for the J1 apps.
version: 1.0.3
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  equatable: ^2.0.5
  get_it: ^8.0.2
  go_router: ^14.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.2
      
  mocktail: ^1.0.4
